config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tube/', include('tube.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tube/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.tube_list, name="tube_list"),
    path("<int:pk>/", views.tube_detail, name="tube_detail"),
    path("create/", views.tube_create, name="tube_create"),
    path("<int:pk>/update/", views.tube_update, name="tube_update"),
    path("<int:pk>/delete/", views.tube_delete, name="tube_delete"),
    path("tag/<str:tag>/", views.tube_tag, name="tube_tag"),
    # comment 삭제 url 추가
    path(
            "<int:pk>/comment_delete/",
            views.tube_comment_delete,
            name="tube_comment_delete",
    ),
    # 구독 url 추가
    path(
            "<int:post_id>/<int:user_id>/subscribe/",
            views.tube_subscribe,
            name="tube_subscribe",
    ),
    # 구독 취소 url 추가
    path(
            "<int:post_id>/<int:user_id>/unsubscribe/",
            views.tube_unsubscribe,
            name="tube_unsubscribe",
    ),
]

tube/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    thumbnail_image = models.ImageField(upload_to='blog/image/%Y/%m/%d/')
    video_file = models.FileField(upload_to='blog/files/%Y/%m/%d/')
    view_count = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    message = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Subscription(models.Model):
    subscriber = models.ForeignKey(
            User, on_delete=models.CASCADE, related_name="subscriptions"
    )
    channel = models.ForeignKey(
            User, on_delete=models.CASCADE, related_name="subscribers"
    )
    subscribed_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("subscriber", "channel")  # 구독자와 채널은 유일해야 함

    def __str__(self):
        return f"{self.subscriber.username}이 {self.channel.username}를 구독하였습니다."

tube/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"


class CommentForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea)

tube/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import CommentForm, PostForm
from .models import Post, Comment, Subscription, User


def tube_list(request):
    # 검색 q가 있을 경우 title과 content에서 해당 내용이 있는지 검색
    q = request.GET.get("q", "")
    if q:
        posts = Post.objects.filter(title__contains=q) | Post.objects.filter(
                content__contains=q
        )
        return render(request, "tube/tube_list.html", {"posts": posts, "q": q})
    posts = Post.objects.all()
    return render(request, "tube/tube_list.html", {"posts": posts})


def tube_comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect("tube_detail", post_pk)


@login_required
def tube_create(request):
    if request.method == "GET":
        form = PostForm()
        context = {"form": form}
        return render(request, "tube/tube_create.html", context)
    elif request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect("tube_list")
        else:
            context = {"form": form}
            return render(request, "tube/tube_create.html", context)


@login_required
def tube_update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # 내가 쓴 게시물만 업데이트 가능
    if post.author != request.user:
        return redirect("tube_list")

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect("tube_detail", pk=post.pk)
    else:
        form = PostForm(instance=post)
        context = {"form": form, "pk": pk}
        return render(request, "tube/tube_update.html", context)


@login_required
def tube_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # 내가 쓴 게시물만 삭제 가능
    if post.author != request.user:
        return redirect("tube_list")

    if request.method == "POST":
        post.delete()
    return redirect("tube_list")


def tube_tag(request, tag):
    posts = Post.objects.filter(tags__name__iexact=tag)
    return render(request, "tube/tube_list.html", {"posts": posts})


def tube_detail(request, pk):
    post = Post.objects.get(pk=pk)
    form = CommentForm()
    is_subscribed = False  # 구독 여부를 확인하는 변수 초기화
    if request.user.is_authenticated:
        # 현재 사용자가 이 포스트의 저자를 구독하고 있는지 확인
        is_subscribed = Subscription.objects.filter(
                subscriber=request.user, channel=post.author
        ).exists()

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            author = request.user
            message = form.cleaned_data["message"]
            c = Comment.objects.create(author=author, message=message, post=post)
            c.save()
    if request.method == "GET":
        post.view_count += 1
        post.save()
    return render(
            request,
            "tube/tube_detail.html",
            {"post": post, "form": form, "is_subscribed": is_subscribed},
    )


@login_required
def tube_subscribe(request, post_id, user_id):
    """구독 추가 뷰"""
    user = request.user  # 현재 로그인한 사용자
    channel = get_object_or_404(User, pk=user_id)  # 구독할 채널(사용자)

    # 이미 구독한 경우 추가하지 않습니다.
    if Subscription.objects.filter(subscriber=user, channel=channel).exists():
        return redirect("tube_detail", pk=post_id)

    # 구독 객체 생성
    q = Subscription.objects.create(subscriber=user, channel=channel)
    q.save()

    return redirect("tube_detail", pk=post_id)


@login_required
def tube_unsubscribe(request, post_id, user_id):
    """구독 취소 뷰"""
    user = request.user  # 현재 로그인한 사용자
    channel = get_object_or_404(User, pk=user_id)  # 구독 취소할 채널(사용자)

    # 구독 객체가 존재하면 삭제합니다.
    Subscription.objects.filter(subscriber=user, channel=channel).delete()
    return redirect("tube_detail", pk=post_id)

templates/tube/tube_create.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

templates/tube/tube_detail.html
{% extends 'base.html' %}
{% block content %}
    <section class="detail-container m-6 space-y-4">

        <video class="w-100" controls>
            <source src="{{ post.video_file.url }}"></source>
        </video>

        <h2 class="font-bold text-xl">{{ post.title }}</h2>
        <p>{{ post.author }}</p>

        <!-- 구독을 했을 경우 구독중 버튼을 구독을 안했을 경우 구독 버튼을 노출-->
        {% if user.is_authenticated and user != post.author %}
            {# {{ post.author.subscribers.all }}를 그냥 순회돌면 쿼리셋입니다. #}
            {% if is_subscribed %}
                <form action="{% url 'tube_unsubscribe' post.pk post.author.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="구독중" class="border border-gray-200 p-2 rounded-lg">
                </form>
            {% else %}
                <form action="{% url 'tube_subscribe' post.pk post.author.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="구독" class="border border-gray-200 p-2 rounded-lg">
                </form>
            {% endif %}
        {% endif %}

        <div class="bg-gray-200 p-4 rounded-lg text-sm">
            <p>조회수 {{ post.view_count }}회 · {{ post.created_at|timesince }} 전</p>
            {{ post.content|linebreaks }}
        </div>

        {% for tag in post.tags.all %}
            <a class="text-blue-600" href="/tube/tag/{{ tag.name }}">#{{ tag.name }}</a>
        {% endfor %}

        <!-- 로그인을 했고, 내가 이 글에 글쓴이라고 한다면 삭제와 업데이트 버튼 노출 -->
        {% if user.is_authenticated and user == post.author %}
            <div class="flex gap-4">
                <a class="border border-gray-200 p-2 rounded-lg" href="{% url 'tube_update' post.pk %}">수정</a>
                <form class="border border-gray-200 p-2 rounded-lg" action="{% url 'tube_delete' post.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="삭제">
                </form>
            </div>
        {% endif %}

        <p class="font-bold text-xl">댓글 {{ post.comments.count }}개</p>
        <form action="" method="post" class="flex p-4 space-y-4 space-x-2 bg-white shadow-md rounded-lg">
            {% csrf_token %}
            <div class="flex w-20 items-center justify-center">
                <label for="id_message" class="text-sm font-medium text-gray-700 text-center">뎃글 작성:</label>
            </div>

            <textarea name="message" cols="40" required="" id="id_message" class="mt-1 block w-3/4 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"></textarea>
            <input type="submit" value="작성" class="py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        </form>

        {% for comment in post.comments.all %}
            <div class="border border-gray-200 p-4 rounded-lg">
                <p><span class="font-bold">{{ comment.author }}</span> · {{ comment.created_at|timesince }} 전</p>
                <p>{{ comment.message }}</p>
                {% if user.is_authenticated and user == comment.author %}
                    <div class="flex gap-4">
                        <form class="" action="{% url 'tube_comment_delete' comment.pk %}" method="post">
                            {% csrf_token %}
                            <input class="text-gray-500 hover:text-gray-800 text-sm" type="submit" value="삭제">
                        </form>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </section>
{% endblock %}

templates/tube/tube_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="grid grid-cols-4 gap-4 p-4 m-6">
        {% for post in posts %}
            <section>
                <!-- 클랙했을 때 해당 게시물로 이동 -->
                <a href="{% url 'tube_detail' post.pk %}">
                    <!-- 썸네일 이미지가 있는지 확인 후 로드 -->
                    {% if post.thumbnail_image %}
                        <img class="w-[100%] rounded-lg" src="{{ post.thumbnail_image.url }}" alt="{{ post.title }}">
                    {% endif %}
                    <h2 class="font-bold">{{ post.title }}</h2>
                    <!-- 조회수와 업로드 날짜 -->
                    <!-- ㄱ 하고 한자 눌러 단축키 입력하세요. -->
                    <p>조회수 {{ post.view_count }}회 · {{ post.created_at|timesince }} 전</p>
                    <p>{{ post.author }}</p>
                    <!-- 태그 추가 -->
                    {% for tag in post.tags.all %}
                        <a href="{% url 'tube_tag' tag.name %}">{{ tag.name }}</a>
                    {% endfor %}
                </a>
            </section>
        {% endfor %}
    </div>
{% endblock %}

templates/tube/tube_update.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>